config/routes.rb
Rails.application.routes.draw do
  scope '/api', defaults: { format: :json } do
    scope '/purchase' do
      post '/:item' => 'apis#purchase'
    end
  end
  get '/home' => "pages#home"
  resources :shops
  resources :customers

  root 'pages#index'

end

app/models/customer.rb
class Customer < ActiveRecord::Base
  has_many :products, through: :sales
end

app/models/preference.rb
class Preference < ActiveRecord::Base
end

app/models/product.rb
class Product < ActiveRecord::Base
  belongs_to :shop

  has_many :customers, through: :sales
end

app/models/sale.rb
class Sale < ActiveRecord::Base
  belongs_to :customer
  belongs_to :product
end

app/models/shop.rb
class Shop < ActiveRecord::Base
  has_many :products
  
  has_secure_password
end

app/controllers/apis_controller.rb
class ApisController < ApplicationController
  before_filter :parse_request, :authenticate_user_from_token!
  skip_before_action :verify_authenticity_token
  @auth = false
  public 
  def purchase
    unless @auth
      render nothing: true, status: :unauthorized
      return
    end
    
    begin
      acknowledgePurchase
      render json: {message: 'Success'}
    rescue => e
      render json: {message: "#{e.message}"}
    end

  end
  private
  def authenticate_user_from_token!
    if !@json['api_token']
      render nothing: true, status: :unauthorized
    else
      # if Devise.secure_compare("42", @json['api_token'])
      if @json['api_token'] == "42"
        @auth = true
      end
    end
  end

  def parse_request
    begin
      @json = JSON.parse(request.body.read)
    rescue
      render json: {message: "Malformed JSON"}
    end
  end

  def acknowledgePurchase
    begin
      customerId = @json['customer']
      quantity = @json['quantity']
    rescue
      raise "Malformed JSON request: customer and quantity need to be supplied"
    end

    begin
      product = Product.find(params[:item])
    rescue ActiveRecord::RecordNotFound
      raise "A product with this ID does not exist"
    end

    begin
      customer = Customer.find(customerId)
    rescue ActiveRecord::RecordNotFound
      raise "A customer with this ID does not exist"
    end

    if product.quantity < quantity then
      raise "Out of stock"
    end

    ActiveRecord::Base.transaction do
      Sale.create(product_id: product.id, customer_id: customer.id, quantity: quantity)
      product.quantity = product.quantity - quantity
      product.save
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  def index
    @customers = Customer.all
  end

  def show
    @customer = Customer.find(params[:id])
    sales = Sale.where customer_id: @customer.id
    @product_sales = []
    sales.each do |sale|
      psale = Hash.new
      psale[:product] = Product.find(sale.product_id)
      psale[:quantity] = sale.quantity
      @product_sales << psale
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
  def index
  end
end

app/controllers/shops_controller.rb
class ShopsController < ApplicationController
  def index
    @shops = Shop.all
  end

  def show
    @shop = Shop.find(params[:id])
    @products = @shop.products
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/customers/index.html.erb
<Style>
body {
  padding-left: 5%;
}
</style>
<h1>Customer List</h1>

<% @customers.each do |customer| %>

<%= link_to customer.name, customer_path(customer) %><br /><br />

<% end %>

app/views/customers/show.html.erb
<h1><%= @customer.id %></h1>

<b>Name: </b><%= @customer.name %><br />
<b>Email: </b><%= @customer.email %><br />
<br />
<br />
<h3>Purchases made</h3>
<table class = "table table-striped">
  <thead>
  <tr>
    <th>Product</th>
    <th>Quantity purchased</th>
  </tr>
  </thead>
  <% @product_sales.each do |sale| %>
  
  	<tr>
   		<td><%= sale[:product].name %></td>
    	<td><%= sale[:quantity] %></td>
  	</tr>
  
  
  <% end %>
</table>	

    

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MyStreet - My Way</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<nav class="navbar navbar-inverse navbar-fixed-top">
<div class = "container">
	
	<a class = "navbar-brand" href="/">MyStreet</a>
	<button class = "navbar-toggle" data-toggle = "collapse" data-target = ".navHeaderCollapse">
	Menu
	</button>
	<div class = "collapse navbar-collapse navHeaderCollapse">
  	<ul class = "nav navbar-nav navbar-right">
  	<li><%= link_to 'Shops', shops_path %></li>
	<li><%= link_to 'Customers', customers_path %></li>
	</ul>
	</div>
	</div>
</nav>

<style>

body {
 padding-top: 60px;
}
</style>

<%= yield %>

</body>
</html>

app/views/pages/home.html.erb
<h1>I will not buy this record, it is scratched</h1>

app/views/pages/index.html.erb
<div class = "container-fluid">
	<div class="col-md-12 text-center">
	<h1>MyStreet - My way!</h1>
	<div>MyStreet</div>
		<div class="col-md-12 text-center">
			<%= image_tag("MLogo.png", alt: "Connect to social media") %>
    	<div><h2>Deals that are made for <i>you.</i></h2></div>
    	
    	
</div>

app/views/shops/index.html.erb
<h1>Shops</h1>
<style>
body {
  padding-left: 5%;
}
</style>
<table>
  <tr>
    <th>Shop name</th>
  </tr>

<% @shops.each do |shop| %>
  <tr>
    <td>
      <%= link_to shop.name, shop_path(shop) %>
    </td>
  </tr>
<% end %>
</table>

app/views/shops/show.html.erb
<h1><%= @shop.name %></h1>

<table class = "table table-striped">
  <thead>
  <tr>
    <th>Product name</th>
    <th>Price per unit</th>
    <th>Quantity in stock</th>
  </tr>
  </thead>
  <% @products.each do |product| %>
  <tr>
    <td>
      <%= product.name %>
    </td>
    <td>
      <%= "£%.2f" % product.price %>
    </td>
    <td>
      <%= product.quantity %>
    </td>
  </tr>
  <% end %>
</table>

  